### ISSUE TITLE
Requête invalide

### ISSUE THREAD

**Issue by Adau** [alphayax/freebox_api_php#1]
J'ai un souci en essayant d'utiliser certaines fonctions du service **FileSystemOperation**.

```php
require_once __DIR__ . '/vendor/autoload.php';

$app = new \alphayax\freebox\utils\Application('com.alphayax.freebox.filesystem', 'Freebox PHP API (FileSystem)', '1.0.0');
$app->authorize();
$app->openSession();

$FSListService = new \alphayax\freebox\api\v3\services\FileSystem\FileSystemListing($app);

try {
    $file = $FSListService->getFileInformation('/Disque dur/Téléchargements/foo.txt');
    var_dump($file);
} catch (Exception $e) {
    echo $e->getMessage();
}
```

Jusque-là, tout va bien, le fichier existe et le service me renvoie les informations. Mais :

```php
$FSListService = new \alphayax\freebox\api\v3\services\FileSystem\FileSystemOperation($app);

try {
    $FSListService->rename('/Disque dur/Téléchargements/foo.txt', 'bar.txt');
} catch (Exception $e) {
    echo $e->getMessage();
}

```

me renvoie une erreur :

> Requête invalide : impossible de parser le json (invalid_request)

Idem en essayant d'utiliser la fonction `move` du même service.
Je n'arrive pas à trouver d'où ça vient, une idée ?

**Comment by alphayax** [comment]
Je confirme le probleme pour avoir réussi a le reproduire de mon coté.
Cette erreur est remontée par l'API de la freebox. Cependant c'est curieux... Le JSON envoyé semble correct. (Documentation dispo ici : https://dev.freebox.fr/sdk/os/fs/#rename-a-file-folder )

Je vais faire des tests de mon coté pour comprendre...

**Comment by alphayax** [comment]
Ok, j'ai identifié le problème : La requête HTTP est mal envoyée par la librairie.
Je vais faire un petit refactor pour fixer cela :)

**Comment by alphayax** [comment]
Je viens de sortir la version 1.2.5 qui doit corriger cela :) 
Il faudra penser a faire un composer update pour mettre a jour les dependances

(Merci de rouvrir l'issue si ca ne fonctionne pas :p )

**Comment by Adau** [comment]
Merci pour la mise à jour !

Je confirme, la fonction `rename` refonctionne correctement.
Par contre, j'ai toujours la même erreur sur les fonctions `move` et `remove` (je n'ai pas testé les autres fonctions de ce service).

**Comment by alphayax** [comment]
xD :) Oui, j'ai fait un fix rapide pour te débloquer.
Je refactorerai le reste dans peu de temps :)

Faut aussi que j'implémente la v4 de l'API... Beaucoup de boulot en perspective...

**Comment by Adau** [comment]
D'accord, merci en tout cas !

**Comment by alphayax** [comment]
J'ai fini de refactorer ce service, et j'ai sorti la version 1.2.6 qui embarque toutes les corrections :)

Tiens moi informé si tu as d'autres soucis :)

**Comment by Adau** [comment]
Super, merci beaucoup !
Je confirme, tout fonctionne.
